### PR TITLE
Move to pyproject.toml

### PR DESCRIPTION
**Pull request by AT0myks**
`setup.py` install has been deprecated for some time now. It's not urgent to upgrade but I thought that was an easy enough change. At the same time I wanted to move the project to another layout since the distribution contains two files but thought I'd get your opinion on that before making a commit. The reason is that if this was a single-module distribution the current layout would be fine, but the presence of `_version.py` means it would be better to have them both in a folder to avoid potential conflicts. Right now both `pakler.py` and it are placed directly inside `site-packages`. I don't know what would happen if you were to install another project that also has a `_version.py`, but I'm guessing the existing one would be overriden.

I've never used `setuptools-scm` before but I see that it "automatically adds all of the SCM-managed files to the sdist". Is this intended in this project? I usually only use `setuptools` and was confused when I saw the `.idea` folder, `.gitignore` and `pakler.iml` in the tar.gz.

### CODE REVIEW

**Comment by vmallet** [comment]
This is great! A lot of the python packaging was new to me when I was trying to ship `pakler` and clearly it could have been improved even back then. Moving to `pyproject.toml` seems to be the right thing indeed. 

Moving to a more isolated layout is definitely a good thing, I would have done it if I had understood more at the time. Happy to get a commit for it :)
And including all these non-distribution files (`.idea` and such) into the distribution is also the result of not quite understanding the packaging aspect of python back then. These should not be included.

If you'd rather add the layout change to this PR I'll wait, otherwise I could merge this PR now.

**Comment by AT0myks** [comment]
The layout change is pushed. Removing `setuptools-scm` wasn't enough for me to get a tar without the extra files. I had to remove some (cache?) files in my project directory to make it work. This might have been related to my environment though, maybe my editable install. Next time you generate distribution packages make sure you don't encounter the same issue, so that the extra files don't get included again even after the "fix".

No worries, the packaging was perfectly fine, and as long as the user can properly use the tool, they probably don't care about the rest. On top of that, since wheels are preferred over the tar.gz these files probably never made their way to anyone.

**Comment by AT0myks** [comment]
Have you had time to look at the new commit?

**Comment by vmallet** [comment]
Sorry @AT0myks, I've been quite behind.
There are a couple of things in the 3rd commit that made me think:
* Moving things into a package makes the distribution cleaner, but moving the whole core functionality into the package's `__init__.py` feels weird. I would have expected `pakler.py` to move into the package and have `__init.py__` do what it needs to do to connect the dots. Reason I've taken so long is because I was hoping to get time to play with it to have a better-formulated comment, but time has been scarce so that's how far I can comment :)
* If I read correctly, we now have a version baked into the code; I liked the idea of deriving the version from the git tag at packaging time, and defaulting to a 'dev' version when running from a local repo. Then we know for sure that the pypi-published version matches the tag in git and it minimizes the risk of error when someone forgets to bump the version in the file. Again, I haven't had time to play with the packaging more but if we could keep `setuptools_scm` in the flow that'd make versioning cleaner.

Thoughts?

**Comment by AT0myks** [comment]
- It's also something that used to feel weird to me because I've often read that `__init__.py` should contain very little code, if any. When I saw that some modules in the standard library have a lot of their functionality in their `__init__.py`, I thought it couldn't be that bad. I think [logging](https://github.com/python/cpython/blob/3.11/Lib/logging/__init__.py) is a good example. Here's my reasoning: if your codebase is small enough that it fits in a single file, I prefer having all the code in `__init__.py` instead of having both an `__init__.py` and a module that has the same name as the package. That's just my preference, and there might be issues with doing it this way (I haven't encountered any so far). As the code grows, you'll add new files to group things in a way that creates a better structure. Now, I don't think there's anything wrong with doing it the way you describe, and if that's what you prefer then I'll make the change in a new commit
- I'm gonna look into reintroducing `setuptools-scm` while keeping away the SCM-managed files from the distributions

**Comment by vmallet** [comment]
Ok cool, good explanation for the `__init__.py` rationale, i'm good with the way it is.

Thanks for taking a crack at  keeping `setuptools-scm`.

**Comment by AT0myks** [comment]
Here's the commit. Unwanted files are excluded from the sdist with [`MANIFEST.in`](https://packaging.python.org/en/latest/guides/using-manifest-in/).

**Comment by vmallet** [comment]
Thanks, it's going in!

**Pull request merged**
